[[commands]]
package = "nodejs_23"
name = "node"

[[commands]]
package = "pnpm"

[devshell]
motd = '''
  {73}🔨 Welcome to the {201}Astro{105}pedia{73} Devshell!{reset}
  $(type -p menu &>/dev/null && menu)

{bold}[[scripts]]{reset}

$(jq -r '( .scripts | to_entries | map("   pnpm " + .key + " - " + .value)) | .[]' package.json)
'''
